chore: add pre-commit and commit-msg hooks for linting and validation

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,14 +1,17 @@
 #!/bin/sh
 # Deteksi sistem operasi
-
 OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
+
 
 if echo "$OS" | grep -q "mingw"; then
   # Windows (Git Bash)
   echo "🔍 Detected Windows (Git Bash). Running PowerShell script..."
-  powershell.exe -ExecutionPolicy Bypass -NoProfile -File .husky/pre-commit.ps1
+  powershell.exe -ExecutionPolicy Bypass -NoProfile -File .husky/commit-msg.ps1 "$1"
 else
   # Linux/Mac
   echo "🔍 Detected Linux/Mac. Running shell script..."
-  bun run lint-staged || (echo "❌ ESLint failed! Please fix errors and warnings first." && exit 1)
+  .husky/commit-msg.sh "$1" || {
+    echo "❌ Commit message invalid. Please fix."
+    exit 1
+  }
 fi
